version: "3.9"

services:
  customer-service:
    build:
      context: .
      dockerfile: CustomerApi/Dockerfile
    ports:
    - 9001:80
    restart: on-failure
  email-service:
    build:
      context: .
      dockerfile: EmailApi/Dockerfile
    ports:
    - 9002:80
    restart: on-failure
  order-service:
    build:
      context: .
      dockerfile: OrderApi/Dockerfile
    ports:
    - 9003:80
    restart: on-failure
  product-service:
    build:
      context: .
      dockerfile: ProductApi/Dockerfile
    ports:
    - 9004:80
    restart: on-failure
  rabbitmq:
    image: rabbitmq:3-management
    ports:
    - "15673:15672"