version: "3.9"

services:
  customer-service:
    build:
      context: .
      dockerfile: CustomerApi/Dockerfile
  email-service:
    build:
      context: .
      dockerfile: EmailApi/Dockerfile
  order-service:
    build:
      context: .
      dockerfile: OrderApi/Dockerfile
    ports:
  product-service:
    build:
      context: .
      dockerfile: ProductApi/Dockerfile
    ports:
  api-gateway:
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports:
    - 8002:80
  rabbitmq:
    image: rabbitmq:3-management
    ports:
    - "15673:15672"