apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: emilwitt/onlineretailerpartial2-order-service:latest 
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: order-service
  ports:
  - port: 80
    nodePort: 31002